---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: &ns argo-system
spec:
  project: ns-cert-manager
  source:
    repoURL: git@github.com:vrsf-homelab/kubernetes.git
    targetRevision: master
    path: manifests/ns-cert-manager/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: *ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
