apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
    namespace: cert-manager
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ENC[AES256_GCM,data:eIXvaTJOKdgi5r6vSTZ5Tfk3vw4C,iv:fOEavewjF+vAHJtUJt9c9LnnmiEsPmk9FdwCd1dsBGw=,tag:T1GXtd714ujrFdTXfk9YQg==,type:str]
        privateKeySecretRef:
            name: letsencrypt-prod
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cloudflare-token
                        key: apiToken
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:542006288021:alias/vrsf-homelab-sops
          created_at: "2024-06-06T23:31:13Z"
          enc: AQICAHgF6injDvjROWdTFk5WjvFDpdnnijlTWIcGuHq8tjJbNgFzKJ1H8BwpFHzrmBoHIkQDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMOyyDitLqDfWuEGHJAgEQgDvHNPl6w6pJ4oVnYy1LEeXYjc/nm3PJAzlQQY8BDhFWRApzWbakr3C/Ms+Qy/Jk0ZvpFgp3Ao8We8FbWg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-06T23:31:14Z"
    mac: ENC[AES256_GCM,data:N8D4FGsEzh1LhN1zCnSzK3vAu0EXb5L+zp+6vdCIzOzN2x8kZWHLx/m9t36qqKRJ+pJ4uwdFoaHHARIdUX6+UWUpsMOXB6JgLiTs/F3lMzkug4WsfRI4B+HfyPSvNnYnjAWxV4OjDinljtMIOQg05roz+bSdKeoY6yjPFsVz+1g=,iv:vMhwXJxK0JDJh+3sDG2+ulkTq3iAiUu/4bpOTKVcizs=,tag:UKJJm7ksfZvxKPOSmTrDvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.1
