apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: cert-manager
type: Opaque
data:
    apiToken: ENC[AES256_GCM,data:BPHXrXeMzQJ/3SJwiBsP0wcMBpunlsw8gWjwQMTDQvEq3bNXEQPXS1tdCOYeqPxa2muzwyVUHu8=,iv:buE+QAIaOxJX8DKp0qNwCTqKftqcjmNLrjlclM6kuTQ=,tag:YIES2MoO0IvL8keaNxfO1g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:542006288021:alias/vrsf-homelab-sops
          created_at: "2024-06-06T23:30:54Z"
          enc: AQICAHgF6injDvjROWdTFk5WjvFDpdnnijlTWIcGuHq8tjJbNgGLWQOzWps85z8E/cuz1dIdAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvTAU0KEM7UheAw1wAgEQgDvWE9gzK9Ty9nZDaArZHvtizWe8ZH94gn+5+StfA1ORu4xLsXRrlMXO8XX34gF9qFsqsQSBNdVzZTjFaQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-06T23:30:54Z"
    mac: ENC[AES256_GCM,data:/TzdxI1Rsh+XhVLMOM51HJ0aSnPDHvEEmqinQi1398AjYsvk10XnJjG6j7WkTAooAclQ2eyGvwUvFhBNITFMYujGHXJVFdZG8eD8mpJXk0tvBVHS+NE+yH2OnqjGXJMSELTJ817CLrUo67x+FMxLsj1Nn30pYRZxDu2AHvWNWfs=,iv:RAo+zjnTmitbyMvtGvXxbXoH8Sff1/Ot0fy4PLf56Js=,tag:mL7YAI0H1jQWFSGwNNdRVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.1
