resources:
  requests:
    cpu: 5m
    memory: 32Mi
  limits:
    cpu: 15m
    memory: 64Mi

metrics:
  controllerManagerAddr: ":8080"
  listenerAddr: ":8080"
  listenerEndpoint: "/metrics"

flags:
  logLevel: debug
  # logFormat: json
  watchSingleNamespace: arc-runners
  excludeLabelPropagationPrefixes:
    - "argocd.argoproj.io/instance"
