apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data-lh-pvc
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-extensions-lh-pvc
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
