apiVersion: v1
kind: Service
metadata:
  name: freshrss-service
  namespace: freshrss
  annotations:
    external-dns.alpha.kubernetes.io/hostname: rss.vrsf.in
spec:
  selector:
    run: freshrss
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
