resources:
  - resources/vso.yaml
  - resources/vso-secrets.yaml

namespace: &namespace prometheus-exporter

helmCharts:
  - name: prometheus-mikrotik-exporter
    repo: https://helm.vrs-factory.dev
    version: 0.4.0 # https://github.com/vertisan/helm-charts/releases
    releaseName: prometheus-mikrotik-exporter
    namespace: *namespace
    valuesFile: values.yaml
