replicaCount: 1

serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus

resources:
  requests:
    cpu: 5m
    memory: 64Mi
  limits:
    cpu: 20m
    memory: 256Mi

config:
  router:
    existingSecret: mikrotik-router-config
  scrapper:
    existingSecret: mikrotik-scrapper-config

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: prometheus-mikrotik-exporter
              app.kubernetes.io/name: prometheus-mikrotik-exporter
          topologyKey: kubernetes.io/hostname

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: prometheus-mikrotik-exporter
        app.kubernetes.io/name: prometheus-mikrotik-exporter
