apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: 1.14.4
  targetNamespace: cert-manager
  createNamespace: true
  valuesContent: |-
    installCRDs: true
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
