apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: sops-generator
  namespace: jenkins
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - resources/secret-controller.enc.yaml
  # - resources/secret-webhook.enc.yaml
