apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudflared-controller
  namespace: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
