---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mikrotik-router-config
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-prometheus-exporter/exporter-mikrotik/mikrotik-router-config
  refreshAfter: 30s
  destination:
    name: mikrotik-router-config
    create: true
  rolloutRestartTargets:
    - name: prometheus-mikrotik-exporter
      kind: Deployment
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mikrotik-scrapper-config
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-prometheus-exporter/exporter-mikrotik/mikrotik-scrapper-config
  refreshAfter: 30s
  destination:
    name: mikrotik-scrapper-config
    create: true
  rolloutRestartTargets:
    - name: prometheus-mikrotik-exporter
      kind: Deployment
