serviceMonitor:
  enabled: true
  defaults:
    labels:
      release: prometheus
  targets:
    - name: vrs-factory
      url: https://vrs-factory.dev
    - name: vrs-factory-pl
      url: https://vrs-factory.pl
    - name: argocd
      url: https://argocd.vrsf.in
    - name: grafana
      url: https://grafana.vrsf.in
    - name: prometheus
      url: https://prometheus.vrsf.in
    - name: jenkins
      url: https://jenkins.vrsf.in/login
