apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ci-cd
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: CI/CD things.

  sourceRepos:
    - "*"

  destinations:
    - namespace: "*"
      server: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ci-cd
  namespace: argo-system
spec:
  generators:
    - git:
        repoURL: git@github.com:vrsf-homelab/kubernetes.git
        revision: &revision master
        directories:
          - path: "manifests/ci-cd/*"
          - path: "manifests/ci-cd/*.disabled"
            exclude: true
          - path: "manifests/ci-cd/*.standalone"
            exclude: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "{{ path.basenameNormalized }}"
      labels:
        app-group: ci-cd
    spec:
      project: ci-cd
      source:
        repoURL: git@github.com:vrsf-homelab/kubernetes.git
        targetRevision: *revision
        path: "{{ path }}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
