apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-singlebinary
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/component: single-binary
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
