apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argo-system
spec:
  project: network
  source:
    repoURL: git@github.com:vrsf-homelab/helm-charts.git
    path: charts/nginx-ingress
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-controller
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
