global:
  storageClass: nfs-csi

master:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 512Mi

sentinel:
  enabled: true

  masterSet: vrs-redis-master

  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 512Mi

metrics:
  enabled: true

  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus
