---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi
  namespace: &ns argo-system
spec:
  project: ns-nfs-csi-system
  source:
    repoURL: git@github.com:vrsf-homelab/kubernetes.git
    targetRevision: master
    path: sapphire/manifests/ns-nfs-csi-system/nfs-csi
  destination:
    server: XXX
    namespace: *ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
