apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: network
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Network things like MetalLB, Ingress, etc.

  sourceRepos:
    - "*"

  destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: ingress-controller
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: metallb-system
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: kube-system
      server: https://kubernetes.default.svc
      name: in-cluster

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
