apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blackbox
  labels:
    release: prometheus
spec:
  groups:
    - name: blackbox.rules
      rules:
        - alert: BlackboxProbeFailed
          expr: |-
            probe_success == 0
          for: 0m
          annotations:
            summary: Blackbox probe failed (instance {{ $labels.instance }})
            description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          labels:
            severity: critical

        - alert: BlackboxProbeHttpFailure
          expr: |-
            probe_http_status_code <= 199 OR probe_http_status_code >= 400
          for: 5m
          annotations:
            summary: Blackbox probe HTTP failure (instance {{ $labels.instance }})
            description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          labels:
            severity: critical
