namespace: &namespace gitlab

resources:
  - resources/namespace.yaml
  - resources/service-monitor.yaml
  - resources/vso.yaml
  - resources/vso-secrets.yaml

helmCharts:
  - releaseName: gitlab-runners
    repo: https://charts.gitlab.io
    name: gitlab-runner
    version: 0.73.2
    namespace: *namespace
    valuesFile: values.yaml
    includeCRDs: true
    apiVersions:
      - monitoring.coreos.com/v1
      - monitoring.coreos.com/v1/ServiceMonitor
