githubConfigUrl: https://github.com/vrsf-homelab
githubConfigSecret: arc-gha-runner

runnerScaleSetName: homelab

minRunners: 0
maxRunners: 3

containerMode:
  type: dind

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node.kubernetes.io/server-type
                operator: In
                values:
                  - crimson
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - "true"
#       - name: runner
#         image: vertisan/dind:26.0-3.19-20240408

controllerServiceAccount:
  name: arc-gha-rs-controller
  namespace: arc-runners
