---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-token
  namespace: cert-manager
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-cert-manager/cert-manager/cloudflare-token
  refreshAfter: 30s
  destination:
    name: cloudflare-token
    create: true
  rolloutRestartTargets:
    - name: cert-manager
      kind: Deployment
