resources:
  - resources/namespace.yaml

namespace: example

helmCharts:
  - name: hello-world
    repo: https://helm.github.io/examples
    version: 0.1.0
    releaseName: hello-world
    namespace: example
    valuesFile: values.yaml
    includeCRDs: true
