---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: vault-auth
  annotations:
    kubernetes.io/service-account.name: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-ns-example
    serviceAccount: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: example-static
spec:
  vaultAuthRef: vault-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-example/example-app
  refreshAfter: 10s
  destination:
    name: static-secret
    # transformation:
    #   excludes:
    #     - .*
    #   templates:
    #     url:
    #       text: |
    #         {{- printf "postgresql://%s:%s@%s/postgres?sslmode=disable" (get .Secrets "username") (get .Secrets "password") "abc" -}}
    create: true
  rolloutRestartTargets:
    - name: example-app
      kind: Deployment
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault:auth-delegator:example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: example
