---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-auth
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: vso-auth
  annotations:
    kubernetes.io/service-account.name: vso-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-ns-example
    serviceAccount: vso-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault:auth-delegator:example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vso-auth
    namespace: example
