apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubernetes-secrets-provider
  namespace: jenkins
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
