---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: jenkins-credentials
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-jenkins/jenkins/credentials
  refreshAfter: 30s
  destination:
    name: jenkins-credentials
    create: true
