apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Storage things like NFS, Longhorn, etc.

  sourceRepos:
    - "*"

  destinations:
    - namespace: longhorn-system
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: nfs-csi-system
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: kube-system
      server: https://kubernetes.default.svc
      name: in-cluster

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storage
  namespace: argo-system
spec:
  generators:
    - git:
        repoURL: git@github.com:vrsf-homelab/kubernetes.git
        revision: master
        directories:
          - path: "manifests/storage/*"
          - exclude: true
            path: "manifests/storage/*.disabled"
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "{{ path.basenameNormalized }}"
      labels:
        app-group: storage
    spec:
      project: storage
      source:
        repoURL: git@github.com:vrsf-homelab/kubernetes.git
        targetRevision: master
        path: "{{ path }}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
