apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  version: 6.7.11
  targetNamespace: argocd
  createNamespace: true
  valuesContent: |-
    global:
      domain: argocd.vrsf.in

      logging:
        format: json

      deploymentStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%

    controller:
      args:
        appResyncPeriod: 60
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
      pdb:
        minAvailable: 1

    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        tls: true

    notifications:
      enabled: false
