apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  version: 6.7.2
  targetNamespace: argocd
  createNamespace: true
  valuesContent: |-
    global:
      domain: acd.vrsf.in

    controller:
      args:
        appResyncPeriod: 60
      resources:
        limits:
          cpu: 500m
          memory: 1Gi

    server:
      service:
        type: LoadBalancer

      certificate:
        enabled: true
        issuer:
          name: 'letsencrypt-prod'
          kind: 'ClusterIssuer'

    notifications:
      enabled: false
