deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  autoscaling:
    enabled: true

  persistence:
    storageClass: nfs-csi
    size: 10Gi

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: "filesystem"
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem # we're storing on filesystem so there's no real persistence here.
        schema: v13
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  hosts:
    - loki.vrsf.in
  tls:
    - secretName: loki-tls
      hosts:
        - loki.vrsf.in

chunksCache:
  allocatedMemory: 2048

test:
  enabled: false

monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
