resources:
  - resources/namespace.yaml
  - resources/pdb.yaml

namespace: &namespace vault-system

helmCharts:
  - name: vault-secrets-operator
    repo: https://helm.releases.hashicorp.com
    version: 0.8.1
    releaseName: vault-secrets-operator
    namespace: *namespace
    valuesFile: values.yaml
    includeCRDs: true
