apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Home of ArgoCD.

  sourceRepos:
    - "*"

  destinations:
    - namespace: "*"
      server: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argo-system
spec:
  generators:
    - git:
        repoURL: git@github.com:vrsf-homelab/kubernetes.git
        revision: &revision master
        directories:
          - path: "manifests/argocd/*"
          - exclude: true
            path: "manifests/argocd/*.disabled"
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "{{ path.basenameNormalized }}"
      labels:
        app-group: argocd
    spec:
      project: argocd
      source:
        repoURL: git@github.com:vrsf-homelab/kubernetes.git
        targetRevision: *revision
        path: "{{ path }}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
