---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflared-certificate
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-cloudflared/cloudflared/cloudflared-certificate
  refreshAfter: 30s
  destination:
    name: cloudflared-certificate
    create: true
  rolloutRestartTargets:
    - name: cloudflared-controller
      kind: Deployment
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflared-credentials
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-cloudflared/cloudflared/cloudflared-credentials
  refreshAfter: 30s
  destination:
    name: cloudflared-credentials
    create: true
  rolloutRestartTargets:
    - name: cloudflared-controller
      kind: Deployment
