---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflared-certificate
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-cloudflared/cloudflared/cloudflared-certificate
  refreshAfter: 30s
  destination:
    name: cloudflared-certificate
    create: true
  rolloutRestartTargets:
    - name: cloudflared-controller
      kind: Deployment
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflared-credentials
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-cloudflared/cloudflared/cloudflared-credentials
  refreshAfter: 30s
  destination:
    name: cloudflared-credentials
    create: true
  rolloutRestartTargets:
    - name: cloudflared-controller
      kind: Deployment
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: config
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-cloudflared/cloudflared/config
  refreshAfter: 30s
  destination:
    name: tunnel-config
    create: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        config.yaml:
          text: |
            {{- printf "tunnel: %s\n" (get .Secrets "tunnelName") -}}
            {{- printf "credentials-file: /etc/cloudflared/creds/credentials.json\n" -}}
            {{- printf "metrics: 0.0.0.0:2000\n" -}}
            {{- printf "no-autoupdate: true\n" -}}
            {{- printf "ingress:\n" -}}
            {{- $ingressHosts := get .Secrets "ingressHosts" -}}
            {{- $hosts := splitList ";" $ingressHosts -}}
            {{- range $k, $v := $hosts -}}
            {{- $hostHeader := printf "httpHostHeader: %s\n" $v -}}
            {{- printf "- hostname: \"%s\"\n" $v -}}
            {{- indent 2 "service: https://nginx-ingress-ingress-nginx-controller.ingress-controller.svc.cluster.local:443\n" -}}
            {{- printf "originRequest:\n" -}}
            {{- indent 4 $hostHeader -}}
            {{- printf "noTLSVerify: true\n" -}}
            {{- end -}}
            - service: http_status:404
  rolloutRestartTargets:
    - name: cloudflared-controller
      kind: Deployment
