---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: repository-vrsf-homelab
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-argo/argocd/repo-vrsf-homelab
  refreshAfter: 10s
  destination:
    name: repository-vrsf-homelab
    create: true
    labels:
      argocd.argoproj.io/secret-type: repo-creds
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-notifications-secret
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-argo/argocd/notifications
  refreshAfter: 10s
  destination:
    name: argocd-notifications-secret
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: aws-credentials
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-argo/argocd/aws-credentials
  refreshAfter: 10s
  destination:
    name: aws-credentials
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: argo-cd-argocd-server
    - kind: Deployment
      name: argo-cd-argocd-dex-server
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-secret
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-argo/argocd/argocd-secret
  refreshAfter: 10s
  destination:
    name: argocd-secret
    create: true
    overwrite: true
  rolloutRestartTargets:
    - kind: Deployment
      name: argo-cd-argocd-server
    - kind: Deployment
      name: argo-cd-argocd-dex-server
    - kind: Deployment
      name: argo-cd-argocd-applicationset-controller
