---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: arc-gha-runner-personal
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-arc-runners/personal/listener
  refreshAfter: 30s
  destination:
    name: arc-gha-runner-personal
    create: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      # It's not a required, I just wanted to play with templates ;}
      templates:
        github_app_id:
          text: '{{- get .Secrets "appId" -}}'
        github_app_installation_id:
          text: '{{- get .Secrets "appInstallationId" -}}'
        github_app_private_key:
          text: '{{- get .Secrets "appPrivateKey" -}}'
