podDisruptionBudget:
  maxUnavailable: 0
  apiVersion: policy/v1

resources:
  requests:
    cpu: 20m
    memory: 256Mi
  limits:
    cpu: 50m
    memory: 512Mi

grafana.ini:
  server:
    root_url: https://grafana.vrsf.in
  auth.ldap:
    enabled: true
    allow_sign_up: true
    config_file: /etc/grafana/ldap.toml

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.vrsf.in
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.vrsf.in

persistence:
  enabled: true
  storageClassName: nfs-csi-retain
  size: 20Gi
  accessModes:
    - ReadWriteMany

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        type: file
        disableDeletion: false
        editable: true
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/default
      - name: "argocd"
        orgId: 1
        type: file
        folder: "ArgoCD"
        disableDeletion: false
        editable: true
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/argocd
      - name: "kubernetes"
        orgId: 1
        type: file
        folder: "Kubernetes"
        disableDeletion: false
        editable: true
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/kubernetes
      - name: "ingress-controller"
        orgId: 1
        type: file
        folder: "Ingress Controller"
        disableDeletion: false
        editable: true
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/ingress-controller
      - name: "istio"
        orgId: 1
        type: file
        folder: "Istio"
        disableDeletion: false
        editable: true
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/istio
dashboardsConfigMaps:
  default: grafana-dashboards-default
  argocd: grafana-dashboards-argocd
  kubernetes: grafana-dashboards-kubernetes
  ingress-controller: grafana-dashboards-ingress-controller
  istio: grafana-dashboards-istio

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Kubernetes
        type: prometheus
        uid: PA37D07FE30048D3A
        access: proxy
        orgId: 1
        url: https://prometheus.vrsf.in
        isDefault: true
      # - name: NAS
      #   type: prometheus
      #   uid: CDJXD4RE6MU4GB
      #   access: proxy
      #   orgId: 1
      #   url: http://10.69.20.1:10190
      #   isDefault: false
      # - name: Homelab
      #   type: loki
      #   uid: ddxl2zug16xhcb
      #   orgId: 1
      #   url: https://loki-gw.vrsf.in
      #   isDefault: false
    deleteDatasources:
      - name: "Homelab"
        orgId: 1
      - name: "NAS"
        orgId: 1
admin:
  existingSecret: grafana-admin-credentials
  userKey: adminUser
  passwordKey: adminPassword

ldap:
  enabled: true
  existingSecret: ldap-config
