---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-credentials
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-grafana/grafana/admin-credentials
  refreshAfter: 30s
  destination:
    name: grafana-admin-credentials
    create: true
  rolloutRestartTargets:
    - name: grafana
      kind: Deployment
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ldap-config
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-grafana/grafana/ldap-config
  refreshAfter: 30s
  destination:
    name: ldap-config
    create: true
  rolloutRestartTargets:
    - name: grafana
      kind: Deployment
