apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  labels:
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/name: alertmanager
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/instance: alertmanager
  jobLabel: alertmanager
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
      scrapeTimeout: 30s
