apiVersion: v1
kind: Secret
metadata:
    name: example-secret
    namespace: example
type: Opaque
data:
    username: ENC[AES256_GCM,data:+hy84xNZ/Uo=,iv:KFcVG/dTaILjYahdZqsRjRtg4kK//VfQBnIoFkw5ZRk=,tag:+7nQ0Q6CUs8PbZrTjBxGVQ==,type:str]
    password: ENC[AES256_GCM,data:jZ2GC4p1j+TwH8GT,iv:woRD+09329ubvsh4Ht334RxOXTgUDD84elVX0+4AKCg=,tag:NtIJ+Syni7re+pGukejTAg==,type:str]
    valueTest: ENC[AES256_GCM,data:DpSoiuN6WqtU2aEG,iv:JLJMA0lZtVxVqyBXTCZjxgYBRQmYRZL9iXQSEV79WgI=,tag:wFQmVFO3zCXflSfHUUSK9w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:542006288021:alias/vrsf-homelab-sops
          created_at: "2024-05-25T12:25:33Z"
          enc: AQICAHj2f6hX57IyUZVNikxpVJx/MjmH6V3LyiVB5s8g4JDAAAFFMTPNgnhCDXUDQNB9zmx3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIcWWE/p7lz9cOLFYAgEQgDu2UScM0r++jKgpCbNH9p2jm0hnAW04KnZNCVl1iFxzAsPuvPjw9WP81EMcZPmmzbPcjwfsFplsMZLd3A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-25T12:25:33Z"
    mac: ENC[AES256_GCM,data:whCd0y/P/Gzjrz1meTF7eQutCQcdrPUxMTKIz+FZq6TqXfmPjIsq/M6XMdyexy9UhPSDfPfyG+jzyecgbyYA5gbuD5r2G62z0dLnetRgynmM4pnpYwAil5O3EuU4ignArqGVUXMe5Z3R45Yewn4qnU6Q9pUyCQLvZG8BdU2aQNM=,iv:wXYcsVhzQhACTm9y78uMEzp0iRdtr+CF6E+B++1cuno=,tag:AMZ9ium6Z4v92zlfTDbarA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
