apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Homelab monitoring stuff like Prometheus, Grafana, alarms, etc.

  sourceRepos:
    - "*"

  destinations:
    - namespace: prometheus
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: grafana
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: kube-system
      server: https://kubernetes.default.svc
      name: in-cluster

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
