apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ci-cd
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: CI/CD things.

  sourceRepos:
    - "*"

  destinations:
    - namespace: jenkins
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: kube-system
      server: https://kubernetes.default.svc
      name: in-cluster

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
