---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-exporter-blackbox
  namespace: &ns argo-system
spec:
  project: ns-prometheus-exporter
  source:
    repoURL: git@github.com:vrsf-homelab/kubernetes.git
    targetRevision: master
    path: manifests/ns-prometheus-exporter/prometheus-exporter-blackbox
  destination:
    server: https://kubernetes.default.svc
    namespace: *ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
