replicas: 2

podDisruptionBudget:
  maxUnavailable: 50%

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: prometheus-blackbox-exporter
        app.kubernetes.io/name: prometheus-blackbox-exporter

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: prometheus-blackbox-exporter
              app.kubernetes.io/name: prometheus-blackbox-exporter
          topologyKey: kubernetes.io/hostname

serviceMonitor:
  enabled: true
  defaults:
    labels:
      release: prometheus
  targets:
    - name: vrs-factory
      url: https://vrs-factory.dev
    - name: vrs-factory-pl
      url: https://vrs-factory.pl
    - name: argocd
      url: https://argocd.vrsf.in
    - name: grafana
      url: https://grafana.vrsf.in
    - name: prometheus
      url: https://prometheus.vrsf.in
    - name: pve-alpha
      url: https://alpha.pve.vrsf.in:8006
    - name: pve-beta
      url: https://beta.pve.vrsf.in:8006
    # - name: jenkins
    #   url: https://jenkins.vrsf.in/login
