podDisruptionBudget:
  maxUnavailable: 50%

serviceMonitor:
  enabled: true
  defaults:
    labels:
      release: prometheus
  targets:
    - name: vrs-factory
      url: https://vrs-factory.dev
    - name: vrs-factory-pl
      url: https://vrs-factory.pl
    - name: argocd
      url: https://argocd.vrsf.in
    - name: grafana
      url: https://grafana.vrsf.in
    - name: prometheus
      url: https://prometheus.vrsf.in
    - name: pve-alpha
      url: https://alpha.pve.vrsf.in:8006
    - name: pve-beta
      url: https://beta.pve.vrsf.in:8006
    # - name: jenkins
    #   url: https://jenkins.vrsf.in/login
