controller:
  image:
    repository: vertisan/jenkins
    tag: "1.1.0"

  installPlugins: false

  admin:
    existingSecret: jenkins-credentials
    userKey: adminUsername
    passwordKey: adminPassword

  jenkinsAdminEmail: hello@vrs-factory.dev

  podDisruptionBudget:
    enabled: true
    apiVersion: "policy/v1"
    maxUnavailable: 1

  updateStrategy:
    type: RollingUpdate

  tolerations:
    - key: dedicated
      operator: Equal
      value: jenkins
      effect: NoSchedule

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hostName: jenkins.vrsf.in
    ingressClassName: nginx
    tls:
      - secretName: jenkins-tls
        hosts:
          - jenkins.vrsf.in

agent:
  image:
    repository: vertisan/jenkins-agent-generic
    tag: "20240605212508"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 512m
      memory: 1024Mi

  podName: jenkins-agent-generic

  yamlTemplate: |-
    apiVersion: v1
    kind: Pod
    spec:
      tolerations:
        - key: dedicated
          operator: Equal
          value: jenkins
          effect: NoSchedule

# additionalAgents:
#   terraform:
#     podName: jenkins-agent-terraform
#     customJenkinsLabels: terraform
#     image:
#       repository: jenkins/jnlp-agent-terraform
#       tag: latest

persistence:
  size: 20Gi
  storageClass: nfs-csi-retain
