controller:
  image:
    repository: vertisan/jenkins
    tag: "0.1.0"

  installPlugins: false

  admin:
    existingSecret: jenkins-credentials
    userKey: adminUsername
    passwordKey: adminPassword

  jenkinsAdminEmail: hello@vrs-factory.dev

  podDisruptionBudget:
    enabled: true
    apiVersion: "policy/v1"
    maxUnavailable: 0

  updateStrategy:
    type: RollingUpdate

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node.kubernetes.io/server-type
                operator: In
                values:
                  - crimson
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - "true"

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hostName: jenkins.vrsf.in
    ingressClassName: nginx
    tls:
      - secretName: jenkins-tls
        hosts:
          - jenkins.vrsf.in

agent:
  image:
    repository: vertisan/jenkins-agent-generic
    tag: "0.3.0"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 512m
      memory: 1024Mi

  podName: jenkins-agent-generic

  yamlTemplate: |-
    apiVersion: v1
    kind: Pod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: In
                    values:
                      - "true"

# additionalAgents:
#   terraform:
#     podName: jenkins-agent-terraform
#     customJenkinsLabels: terraform
#     image:
#       repository: jenkins/jnlp-agent-terraform
#       tag: latest

persistence:
  size: 20Gi
  storageClass: nfs-csi-retain
