apiVersion: v1
kind: Secret
metadata:
    name: argocd-notifications-secret
    namespace: argo-system
type: Opaque
data:
    slack-token: ENC[AES256_GCM,data:8ri2u+yy5o/IKTDtRccOIM8O+Uet2itVarK6pnBg+qLwMP8CtTcmWdIo26BdEWRsT65fF6H22N96O44WD4G+3qg61BBfJ7dN5bLZpw==,iv:GDrO7vws05BxYiwaO0bo88MwXcoeAe0gtN1pz+GiaTA=,tag:RBysHU8bNOZPzs1EHNyf3g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:542006288021:alias/vrsf-homelab-sops
          created_at: "2024-06-08T18:38:16Z"
          enc: AQICAHgF6injDvjROWdTFk5WjvFDpdnnijlTWIcGuHq8tjJbNgFfydJez0UxPUQ4m0KcNFsNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcjE3CGyf1WvWikHVAgEQgDtnzFZ2eYIPOMPGEskL0ho8GKVQU63bMDHQEaLQq1qP5rdC1ZWh+EAoBMKYJrIOJsbJxox2Cq3jv700iA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-08T18:38:16Z"
    mac: ENC[AES256_GCM,data:i1NRNhMtQzBaxWnrbdU4LX/eTAa0/zQwIWkAghLh0E+2gz8S0P6a2e6ml/eAtL7uXsTgA5qf8IpkNMMO3qeKs81srmYFG50DNErEqjEOacTtQyEGiSzaF3DhGYF95JyLI9ymMIbZhGfTzRsYbBge0xDBSmJyyd5IQhNb0QSGZ4U=,iv:I/gH8QKa1B7tg16BkYzLbvvO7PfFzsPNv3wIs+wsuFY=,tag:qFnB8/Zwf4lgBsv/PV5Izg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|dex.authentik.clientSecret)$
    version: 3.8.1
