apiVersion: v1
kind: Secret
metadata:
    name: argocd-notifications-secret
    namespace: argo-system
type: Opaque
data:
    slack-token: ENC[AES256_GCM,data:wzpmqDgbPW35mL0hB9d0RDTXRTQwslUQx+HN8idEfCVG/uJ5f2VhrYNSvLO5YF/qTHj52kBIgwqK,iv:sISv1BEVy6E94/77bukQXalsMDJq+IhP4/hc2wLOOEw=,tag:9y/wRxbPRzT90qppsyVSQA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:542006288021:alias/vrsf-homelab-sops
          created_at: "2024-06-08T17:35:58Z"
          enc: AQICAHgF6injDvjROWdTFk5WjvFDpdnnijlTWIcGuHq8tjJbNgFHDWvf6Z3jOr6mspeoVNtnAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6tdWJ91iPOHc37j2AgEQgDvjeYJe8zQaOJwi1Zm4X+294RZgcCEi/G/0tPJ8jL/X5ZrqhPwrblKsObVYcRoPoNE891Jj5DwGefy94g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-08T17:35:59Z"
    mac: ENC[AES256_GCM,data:TcqLFh+LwaUaCBKhO0K7s/ilHCso4dZVGJbsSv/ueC4l8A7kF7lvSgJIoSYcn7q7PP+RzAIxzX3Wz6+KCyjNYSwjL6CaFIorm3NLzgPZ72WddJLYIIQkPCtA8obMO62K+PTOzD7yP8pMmNYsAds+47BO+hv4LbR5AtSj0CQP3KE=,iv:F3VXcz9LBy/04wgp6kUFlczhQJRe0Yl4IJGyXZJEwIc=,tag:N6NSrnvubD45QT8+N5vlkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|dex.authentik.clientSecret)$
    version: 3.8.1
