apiVersion: v1
kind: Secret
metadata:
    name: argocd-notifications-secret
    namespace: argo-system
    labels:
        app.kubernetes.io/component: notifications-controller
        app.kubernetes.io/instance: argo-cd
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: argocd-notifications-controller
        app.kubernetes.io/part-of: argocd
        argocd.argoproj.io/instance: argocd
type: Opaque
data:
    slack-token: ENC[AES256_GCM,data:WuE4/1ebWdxdfHa8apBVoS5RhcsQhQd4675XOD6p/6+WzNhKlfrTaVZGP5HLOxW0Qp+JhHYvzWDIzb3SKMojQNoc9AHy6jWJL0A4Vw==,iv:kZQL9KcTKjiaB/HziHNJ9pd9fb/jgn5gpxdV0BCHo3o=,tag:QdNtJtdKLbL8nFAcpstCIQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:542006288021:alias/vrsf-homelab-sops
          created_at: "2024-06-08T20:45:26Z"
          enc: AQICAHgF6injDvjROWdTFk5WjvFDpdnnijlTWIcGuHq8tjJbNgHXC5FmUoI9g5eeFoZ0llBwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQopWkzNmOTmU8dCgAgEQgDsAK0m755f6z52IIoNNT8n1ix2jKRj/90UceWroyEfud40FexlFRnDD9dxRSoz9/OknGZxWfGxYIPHahQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-08T20:45:27Z"
    mac: ENC[AES256_GCM,data:2l1LN556YEBkvG/tV9SeyNH9Yw0csGoxszNga8wOlI8NNjD3KZTHKB6bk6fBC0rzxz0irJ10oImQNpYDCRcoGTZFN7jUWOcAOnMP8vlFb5QY2pBiJkHfFjQeF3x1ov8sc88m08E5UfIbN8GoEIgm6w7gbacxVjsQ8Ca/77fd1+o=,iv:4VRg7YKOTPLANuKaghtetCMFfrL0e7Leg5VxY9T06T8=,tag:M7WjibJAaAIDAxPTX5+MJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|dex.authentik.clientSecret)$
    version: 3.8.1
