apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: argo-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:giEAC/jgQ10mm173W57+JQHprcbRtfMb7+8fvg==,iv:sCLtPWr7YLmtGDDMb8yt1Yn0XmNiOdhXmMKMQgXdI4A=,tag:xtuHtjOmJLvO6W3LUxPEqg==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:f28ak3wheetghBaMQM0vzw==,iv:+Vy2c/vwmCDWEWb5OWoTet02Xx5/CgKQk7jm1zRblss=,tag:1zulDGvtbSysRQC6tCE6XA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4hS6BlRs+Jpd/mStLJu/XhPgK+W00WknLzqJL8jnUStc6BzszT0tTA==,iv:x9uOiH2qX1LCJguTh34ZqlGYbe82OG928/qwGYp+oZ4=,tag:IcxpDPVJXycQGsNu7Wik6A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:542006288021:alias/vrsf-homelab-sops
          created_at: "2024-06-06T23:14:37Z"
          enc: AQICAHgF6injDvjROWdTFk5WjvFDpdnnijlTWIcGuHq8tjJbNgEDwD1QAN9ruXQOORsd+fP4AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqPXF7JN8QuQc3V6aAgEQgDv7r9FnRYZ5ucemS4R4qAwakeZhxxt7tev1Fwu/Y7oVVHfF728iB8xrvZxawacnjUBqiItPwEXRonORiQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-06T23:14:38Z"
    mac: ENC[AES256_GCM,data:voF7rxSFnZOZf7QdDd2MGEw2JJn3bryssqxJkvWeDu2TuGFv+PsxWgqzf06uHIhpBLDpoYzHkcR2rNHQQoWAjZ9VBWmClhSkgj1eug2BEyCNKcTYlRTWX81lsIgOEaB3/xvnMSchbPFEOBiyUaWQm2/g/WQNBDogUYjVKv1j5o8=,iv:ecf8l3XTwug3pueE8CXF+dA3Oqg3W6N7htgtDHFeJcw=,tag:nWTlHkjRO3E40DHhAv2jNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|dex.authentik.clientSecret)$
    version: 3.8.1
