#### These monitors are here due to problem with resolving api-version for monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
    release: prometheus
  name: argo-cd-argocd-application-controller
  namespace: argo-system
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
      - argo-system
  selector:
    matchLabels:
      app.kubernetes.io/component: application-controller
      app.kubernetes.io/instance: argo-cd
      app.kubernetes.io/name: argocd-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: applicationset-controller
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/part-of: argocd
    release: prometheus
  name: argo-cd-argocd-applicationset-controller
  namespace: argo-system
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
      - argo-system
  selector:
    matchLabels:
      app.kubernetes.io/component: applicationset-controller
      app.kubernetes.io/instance: argo-cd
      app.kubernetes.io/name: argocd-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/part-of: argocd
    release: prometheus
  name: argo-cd-argocd-dex-server
  namespace: argo-system
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
      - argo-system
  selector:
    matchLabels:
      app.kubernetes.io/component: dex-server
      app.kubernetes.io/instance: argo-cd
      app.kubernetes.io/name: argocd-dex-server
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
    release: prometheus
  name: argo-cd-argocd-notifications-controller
  namespace: argo-system
spec:
  endpoints:
    - path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
      - argo-system
  selector:
    matchLabels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/instance: argo-cd
      app.kubernetes.io/name: argocd-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
    release: prometheus
  name: argo-cd-argocd-redis
  namespace: argo-system
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
      - argo-system
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/instance: argo-cd
      app.kubernetes.io/name: argocd-redis
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
    release: prometheus
  name: argo-cd-argocd-repo-server
  namespace: argo-system
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
      - argo-system
  selector:
    matchLabels:
      app.kubernetes.io/component: repo-server
      app.kubernetes.io/instance: argo-cd
      app.kubernetes.io/name: argocd-repo-server-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    release: prometheus
  name: argo-cd-argocd-server
  namespace: argo-system
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
      - argo-system
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argo-cd
      app.kubernetes.io/name: argocd-server-metrics
