---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: repository-vrsf-homelab
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-argo/argocd/repo-vrsf-homelab
  refreshAfter: 10s
  destination:
    name: repository-vrsf-homelab
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-notifications-secret
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-argo/argocd/notifications
  refreshAfter: 10s
  destination:
    name: argocd-notifications-secret
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: aws-credentials
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-argo/argocd/aws-credentials
  refreshAfter: 10s
  destination:
    name: aws-credentials
    create: true
