resources:
  - resources/namespace.yaml

namespace: &namespace cert-manager

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.14.5
    releaseName: cert-manager
    namespace: *namespace
    valuesFile: values.yaml
    includeCRDs: true

generators:
  - generators/sops-generator.yaml
