resources:
  - resources/namespace.yaml

## https://github.com/kubernetes-sigs/kustomize/issues/4593
# namespace: &namespace cert-manager

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.14.5
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml
    includeCRDs: true

generators:
  - generators/sops-generator.yaml
