resources:
  - resources/namespace.yaml
  - resources/cluster-issuer.yaml
  - resources/vso.yaml
  - resources/vso-secrets.yaml

## https://github.com/kubernetes-sigs/kustomize/issues/4593
# namespace: &namespace cert-manager

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.15.0 # https://github.com/cert-manager/cert-manager/releases
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml
    includeCRDs: true
