crds:
  enabled: true
  keep: true

podDisruptionBudget:
  enabled: true
  maxUnavailable: 0
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 256Mi
extraArgs:
  - --logging-format=json
webhook:
  extraArgs:
    - --logging-format=json
cainjector:
  extraArgs:
    - --logging-format=json

prometheus:
  enabled: true

  servicemonitor:
    enabled: true
    labels:
      release: prometheus

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
