apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-argocd
  namespace: cloudflared
  labels:
    cloudflared-tunnel: argocd-homelab
spec:
  selector:
    matchLabels:
      app: cloudflared-argocd
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared-argocd
    spec:
      containers:
        - name: cloudflared-argocd
          image: cloudflare/cloudflared:2024.3.0
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
            - name: cert
              mountPath: /etc/cloudflared/cert
              readOnly: true
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
      volumes:
        - name: creds
          secret:
            secretName: cloudflared-tunnel-argocd-credentials
        - name: cert
          secret:
            secretName: cloudflared-domain-vrsfin-certificate
        - name: config
          configMap:
            name: cloudflared-config-argocd
            items:
              - key: config.yaml
                path: config.yaml
