resources:
  - resources/namespace.yaml
  - resources/ingress-vault.yaml

namespace: &namespace ingress-controller

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.11.2 # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx?modal=changelog
    releaseName: nginx-ingress
    namespace: *namespace
    valuesFile: values.yaml
    includeCRDs: true
