githubConfigUrl: https://github.com/vrsf-homelab
githubConfigSecret: arc-gha-runner-homelab

runnerScaleSetName: homelab

minRunners: 1
maxRunners: 5

containerMode:
  type: dind

template:
  spec:
    containers:
      - name: runner
        image: vertisan/github-actions-runner:0.23210.0
        command: ["/home/runner/run.sh"]
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist

controllerServiceAccount:
  name: arc-gha-rs-controller
  namespace: arc-runners
