deploymentMode: SingleBinary

singleBinary:
  replicas: 1 # SingleBinary cannot be scaled more than 1
  autoscaling:
    enabled: true

  persistence:
    storageClass: nfs-csi
    size: 20Gi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: loki
            topologyKey: kubernetes.io/hostname

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 2
  storage:
    type: "filesystem"
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem # we're storing on filesystem so there's no real persistence here.
        schema: v13
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0

gateway:
  replicas: 2
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    hosts:
      - host: loki-gw.vrsf.in
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: loki-gw-tls
        hosts:
          - loki-gw.vrsf.in

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: gateway
            topologyKey: kubernetes.io/hostname
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: gateway

chunksCache:
  allocatedMemory: 2048

test:
  enabled: false

monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
