---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: example-secret
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-example/example-app
  refreshAfter: 30s
  destination:
    name: example-secret
    create: true
  rolloutRestartTargets:
    - name: example-app
      kind: Deployment
