apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-runners
  labels:
    app: gitlab-runners
    release: prometheus
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - gitlab
  selector:
    matchLabels:
      app: gitlab-runners
