---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitlab-runner
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-gitlab/runner
  refreshAfter: 30s
  destination:
    name: gitlab-runner
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: runner-cache
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  path: kubernetes/ns-gitlab/runner-cache
  refreshAfter: 30s
  destination:
    name: s3access
    create: true
