---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: &ns argo-system
spec:
  project: ns-argo-system
  source:
    repoURL: git@github.com:vrsf-homelab/kubernetes.git
    targetRevision: master
    path: manifests/ns-argo-system/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: *ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
