namespace: &ns argo-system

resources:
  - resources/namespace.yaml
  - resources/vso.yaml
  - resources/vso-secrets.yaml

helmCharts:
  - name: argo-cd
    releaseName: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 7.8.0 # https://artifacthub.io/packages/helm/argo/argo-cd?modal=changelog
    namespace: *ns
    valuesFile: values.yaml
    additionalValuesFiles:
      - values-notifications.yaml
    includeCRDs: true
    apiVersions:
      - monitoring.coreos.com/v1
