apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in.vrsf.freshrss
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: in.vrsf.freshrss
    repoURL: 'https://github.com/vrsf-homelab/kubernetes.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
