apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in.vrsf.freshrss
  namespace: argocd
spec:
  project: default
  source:
    path: in.vrsf.freshrss
    repoURL: 'https://github.com/vrsf-homelab/kubernetes.git'
    targetRevision: HEAD
  destination:
    namespace: freshrss
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
