namespace: &namespace jenkins

resources:
  - resources/namespace.yaml
  - resources/role.yaml
  - resources/role-binding.yaml
  - resources/vso.yaml
  - resources/vso-secrets.yaml

helmCharts:
  - name: jenkins
    releaseName: jenkins
    repo: https://charts.jenkins.io
    version: 5.1.26 # https://artifacthub.io/packages/helm/jenkinsci/jenkins?modal=changelog
    namespace: *namespace
    valuesFile: values.yaml
    includeCRDs: true
