apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
  labels:
    cloudflared-tunnel: cloudflared-homelab
data:
  config.yaml: |
    tunnel: homelab
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: "grafana.vrsf.in"
      service: https://nginx-ingress-ingress-nginx-controller.ingress-controller.svc.cluster.local:443
      originRequest:
        httpHostHeader: grafana.vrsf.in
        noTLSVerify: true
    - service: http_status:404
