apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ns-ingress-controller
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - "*"

  destinations:
    - namespace: "*"
      server: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
