---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: &ns argo-system
  labels:
    argocd.argoproj.io/group: observability
    argocd.argoproj.io/managed-by: application
  annotations:
    notifications.argoproj.io/subscribe.on-deleted.slack: homelab-argocd
    notifications.argoproj.io/subscribe.on-health-degraded.slack: homelab-argocd
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: homelab-argocd
    notifications.argoproj.io/subscribe.on-sync-failed.slack: homelab-argocd
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: homelab-argocd
spec:
  project: observability
  source:
    repoURL: git@github.com:vrsf-homelab/kubernetes.git
    targetRevision: master
    path: manifests/observability/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: *ns
  ignoreDifferences:
    - group: "admissionregistration.k8s.io/v1"
      kind: ValidatingWebhookConfiguration
      name: prometheus-kube-prometheus-admission
      jsonPointers:
        - ".webhooks[].clientConfig.caBundle"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
