apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo-system
spec:
  project: observability
  source:
    repoURL: git@github.com:vrsf-homelab/helm-charts.git
    path: charts/prometheus
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
