grafana:
  enabled: false

prometheus:
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 0
  prometheusSpec:
    retention: 14d
    resources:
      requests:
        cpu: 250m
        memory: 256m
      limits:
        cpu: 1500m
        memory: 3072Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-csi
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 50Gi

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    ingressClassName: nginx
    hosts:
      - prometheus.vrsf.in
    paths:
      - /
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.vrsf.in

kube-state-metrics:
  metricLabelsAllowlist:
    - nodes=[*]
    - namespaces=[*]
    - pods=[*]

alertmanager:
  enabled: false
