apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: network
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Network things like MetalLB, Ingress, etc.

  sourceRepos:
    - "*"

  destinations:
    - namespace: "*"
      server: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: network
  namespace: argo-system
spec:
  generators:
    - git:
        repoURL: git@github.com:vrsf-homelab/kubernetes.git
        revision: &revision master
        directories:
          - path: "manifests/network/*"
          - path: "manifests/network/*.disabled"
            exclude: true
          - path: "manifests/network/*.standalone"
            exclude: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "{{ path.basenameNormalized }}"
      labels:
        app-group: network
    spec:
      project: network
      source:
        repoURL: git@github.com:vrsf-homelab/kubernetes.git
        targetRevision: *revision
        path: "{{ path }}"
      destination:
        server: https://kubernetes.default.svc
      ignoreDifferences:
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: bgppeers.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: addresspools.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
