apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
spec:
  repo: https://metallb.github.io/metallb
  createNamespace: true
  chart: metallb
  version: 0.14.3
  targetNamespace: metallb-system
  valuesContent: |-
    speaker:
      resources:
        limits:
          cpu: 75m
          memory: 150Mi
    controller:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
