speaker:
  resources:
    requests:
      cpu: 15m
      memory: 150Mi
    limits:
      cpu: 30m
      memory: 256Mi

controller:
  resources:
    requests:
      cpu: 5m
      memory: 72Mi
    limits:
      cpu: 20m
      memory: 128Mi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
