{
 "title": "Mikrotik - General",
 "description": "Mikrotik MKTXP Exporter metrics",
 "tags": [
  "mikrotik",
  "mktxp"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Routerboard",
    "query": {
     "query": "label_values(mktxp_system_identity_info, routerboard_name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Identity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_system_identity_info{routerboard_name=\"$node\"}  ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Routerboard HW",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_system_uptime{routerboard_name=\"$node\"}",
     "legendFormat": "{{board_name}}"
    }
   ]
  },
  {
   "title": "Installed Packages",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "mktxp_installed_packages_info{routerboard_name=\"$node\"}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "(1 - mktxp_system_free_memory{routerboard_name=\"$node\"} / mktxp_system_total_memory{routerboard_name=\"$node\"})*100",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used RAM Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mktxp_system_cpu_load{routerboard_name=\"$node\"}",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - mktxp_system_free_hdd_space{routerboard_name=\"$node\"} / mktxp_system_total_hdd_space{routerboard_name=\"$node\"})*100",
     "legendFormat": "HDD Utilization"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "expr": "mktxp_system_cpu_load{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "CPU 1 load" },
     "legendFormat": "{{cpu}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mktxp_system_cpu_frequency{routerboard_name=\"$node\"}*1000000",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "{{cpu}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_system_cpu_frequency{routerboard_name=\"$node\"}*1000000",
     "legendFormat": "{{cpu}} "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mktxp_system_routerboard_temperature{routerboard_name=\"$node\"}  ",
     "legendFormat": "__auto"
    },
    {
     "expr": "mktxp_system_cpu_temperature{routerboard_name=\"$node\"}  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_uptime{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "legendFormat": "Current: {{version}} ",
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mktxp_system_update_available{routerboard_name=\"$node\"}",
     "legendFormat": "Latest available: {{newest_version}}"
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_uptime{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "mktxp_active_users_info{routerboard_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "HDD Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mktxp_system_total_hdd_space{routerboard_name=\"$node\"} - mktxp_system_free_hdd_space{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Memory" },
     "expr": "mktxp_system_total_hdd_space{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Total memory" },
     "legendFormat": "Total memory",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_routerboard_voltage{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "IP Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_public_ip_address_info{routerboard_name=\"$node\"}",
     "legendFormat": "{{routerboard_address}}"
    }
   ]
  },
  {
   "title": "Public Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_public_ip_address_info{routerboard_name=\"$node\"}",
     "legendFormat": "{{public_address}}"
    },
    {
     "expr": "mktxp_public_ip_address_info{routerboard_name=\"$node\"}",
     "legendFormat": "{{dns_name}}"
    }
   ]
  },
  { "title": "Internet Bandwidth & Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Internet Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "mktxp_internet_bandwidth", "legendFormat": "{{direction}}" }
   ]
  },
  {
   "title": "Internet Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "mktxp_internet_latency", "legendFormat": "latency" }
   ]
  },
  {
   "title": "DHCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IP Pool Usage",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_ip_pool_used{routerboard_name=\"$node\"} ",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ pool }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "DHCP Leases",
     "type": "table",
     "gridPos": { "h": 12, "w": 19, "x": 5, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "mktxp_dhcp_lease_info{routerboard_name=\"$node\"}"
      }
     ]
    },
    {
     "title": "DHCP Leases by Server",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_dhcp_lease_active_count{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ server }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Total DHCP Leases",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "sum(mktxp_dhcp_lease_active_count{routerboard_name=\"$node\"})",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "In - {{ server }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Routes",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mktxp_routes_total_routes{routerboard_name=\"$node\"}"
      }
     ]
    },
    {
     "title": "Routes per protocol",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 4, "x": 2, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_routes_protocol_count{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/errors on interface/" },
       "legendFormat": "{{protocol}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Ethernet Ports: Full Duplex",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mktxp_interface_full_duplex{routerboard_name=\"$node\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Interface Errors",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_interface_rx_error_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/errors on interface/" },
       "legendFormat": "In Errors | {{name}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "expr": "rate(mktxp_interface_tx_error_total{routerboard_name=\"$node\"}[4m])",
       "legendFormat": "Out Errors | {{name}}"
      }
     ]
    },
    {
     "title": "Ethernet Ports: Status",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "mktxp_interface_status{routerboard_name=\"$node\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Rates",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "mktxp_interface_rate{routerboard_name=\"$node\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "POE",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "mktxp_poe_info{routerboard_name=\"$node\"}"
      }
     ]
    },
    {
     "title": "Interface traffic ",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_interface_rx_byte_total{routerboard_name=\"$node\"}[4m])*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "In | {{ name }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_interface_tx_byte_total{routerboard_name=\"$node\"}[4m])*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Outgoing traffic on interface ether1-gateway"
       },
       "legendFormat": "Out | {{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Firewall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Open Connections",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mktxp_connection_stats{routerboard_name=\"$node\"}"
      }
     ]
    },
    {
     "title": "Open Connections Stats",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mktxp_connection_stats{routerboard_name=\"$node\"}",
       "legendFormat": "{{dhcp_name}}"
      }
     ]
    },
    {
     "title": "Logged Firewall Rules Traffic ",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_firewall_filter_total{routerboard_name=\"$node\", log=\"1\"}[4m])*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Logged Raw Firewall Rules Traffic ",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_firewall_raw_total{routerboard_name=\"$node\", log=\"1\"}[4m])*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Firewall Rules Traffic ",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_firewall_filter_total{routerboard_name=\"$node\"}[4m])*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Raw Firewall Rules Traffic ",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_firewall_raw_total{routerboard_name=\"$node\"}[4m])*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Wireless",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Noise Floor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "expr": "mktxp_wlan_noise_floor{routerboard_name=\"$node\"}",
       "legendFormat": "{{channel}}"
      }
     ]
    },
    {
     "title": "Overall Tx CCQ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "mktxp_wlan_overall_tx_ccq{routerboard_name=\"$node\"}",
       "legendFormat": "{{channel}}"
      }
     ]
    },
    {
     "title": "Client Devices",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "mktxp_wlan_clients_devices_info{routerboard_name=\"$node\"}"
      }
     ]
    },
    {
     "title": "Number of clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "mktxp_wlan_registered_clients{routerboard_name=\"$node\"}",
       "legendFormat": "{{channel}}"
      }
     ]
    },
    {
     "title": "WLAN Clients Tx CCQ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "mktxp_wlan_clients_tx_ccq{routerboard_name=\"$node\"}",
       "legendFormat": "{{dhcp_name}}"
      }
     ]
    },
    {
     "title": "Clients Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_wlan_clients_tx_bytes_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "In - {{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_wlan_clients_rx_bytes_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Outgoing traffic on interface ether1-gateway"
       },
       "legendFormat": "Out - {{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Clients Signal Strength",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_wlan_clients_signal_strength{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Clients  Signal-to-Noise ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_wlan_clients_signal_to_noise{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "MKTXP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "MKTXP Collection Times",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_collection_time_total{routerboard_name=\"$node\"}[4m])  ",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "MKTXP Collection Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_collection_time_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "expr": "sum(rate(mktxp_collection_time_total{routerboard_name=\"$node\"}[4m]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  }
 ]
}