helmCharts:
  - name: descheduler
    repo: https://kubernetes-sigs.github.io/descheduler/
    version: 0.30.1 # https://github.com/kubernetes-sigs/descheduler/releases
    releaseName: descheduler
    namespace: kube-system
    valuesFile: values.yaml
    includeCRDs: true
