apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-blackbox
  namespace: argo-system
spec:
  project: observability
  source:
    repoURL: git@github.com:vrsf-homelab/helm-charts.git
    path: charts/prometheus-blackbox
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
