apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo-system
spec:
  project: argocd
  source:
    repoURL: git@github.com:vrsf-homelab/helm-charts.git
    path: charts/argocd
    targetRevision: master
    helm:
      valueFiles:
        - secrets://values.secrets.enc.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
