replicas: 2

podDisruptionBudget:
  maxUnavailable: 50%

resources:
  requests:
    memory: 32Mi
    cpu: 10m
  limits:
    memory: 48Mi
    cpu: 15m

secretConfig: true

config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: true
        preferred_ip_protocol: "ip4"
        fail_if_ssl: false
        fail_if_not_ssl: false
        tls_config:
          insecure_skip_verify: false

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: prometheus-blackbox-exporter
        app.kubernetes.io/name: prometheus-blackbox-exporter

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: prometheus-blackbox-exporter
              app.kubernetes.io/name: prometheus-blackbox-exporter
          topologyKey: kubernetes.io/hostname

serviceMonitor:
  enabled: true
  defaults:
    labels:
      release: prometheus
  targets:
    - name: vrs-factory
      url: https://vrs-factory.dev
    - name: vrs-factory-pl
      url: https://vrs-factory.pl
    - name: argocd
      url: https://argocd.vrsf.in
    - name: grafana
      url: https://grafana.vrsf.in
    - name: prometheus
      url: https://prometheus.vrsf.in
    - name: pve-alpha
      url: https://10.0.20.31:8006
      module: http_2xx
    - name: pve-beta
      url: https://10.0.20.32:8006
    # - name: pve-charlie
    #   url: https://10.0.20.33:8006
    - name: pve-tango
      url: https://10.0.20.34:8006
