# TODO: Separate runners from controller
namespace: &namespace arc-runners

resources:
  - resources/vso.yaml
  - resources/vso-secrets.yaml

helmCharts:
  - releaseName: arc-runner-personal
    name: gha-runner-scale-set
    version: 0.9.3
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    namespace: *namespace
    valuesFile: values.yaml
    includeCRDs: true
