apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-secrets-provider
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes-secrets-provider
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins
