resources:
  - resources/namespace.yaml
  - resources/vso.yaml
  - resources/vso-secrets.yaml

namespace: &namespace grafana

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 8.0.0 # https://github.com/grafana/helm-charts/releases?q=grafana-&expanded=true
    releaseName: grafana
    namespace: *namespace
    valuesFile: values.yaml
    includeCRDs: true

# generators:
#   - generators/sops-generator.yaml

configMapGenerator:
  - name: grafana-dashboards-default
    options:
      disableNameSuffixHash: true
    files:
      - configs/dashboards/default/blackbox-general.json
      - configs/dashboards/default/ga-general.json
      - configs/dashboards/default/mikrotik-general.json
      - configs/dashboards/default/proxmox-general.json
      - configs/dashboards/default/redis.json
      - configs/dashboards/default/cert-manager.json
      - configs/dashboards/default/logs.json

  - name: grafana-dashboards-argocd
    options:
      disableNameSuffixHash: true
    files:
      - configs/dashboards/argocd/argocd-general.json
      - configs/dashboards/argocd/argocd-application-overview.json
      - configs/dashboards/argocd/argocd-operational-overview.json

  - name: grafana-dashboards-kubernetes
    options:
      disableNameSuffixHash: true
    files:
      - configs/dashboards/kubernetes/k8s-general.json
      - configs/dashboards/kubernetes/k8s-nodes.json
      - configs/dashboards/kubernetes/k8s-pods.json

  - name: grafana-dashboards-ingress-controller
    options:
      disableNameSuffixHash: true
    files:
      - configs/dashboards/ingress-controller/nginx-ingress-controller.json
      - configs/dashboards/ingress-controller/nginx-ingress-performance.json

  - name: grafana-dashboards-istio
    options:
      disableNameSuffixHash: true
    files:
      - configs/dashboards/istio/istio-control-plane.json
      - configs/dashboards/istio/istio-mesh.json
      - configs/dashboards/istio/istio-performance.json
      - configs/dashboards/istio/istio-service.json
      - configs/dashboards/istio/istio-wasm-extension.json
      - configs/dashboards/istio/istio-workload.json
      - configs/dashboards/istio/istio-ztunnel.json
