apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
data:
    credentials.json: ENC[AES256_GCM,data:DTQHyUspFiYHDj+N2ApGccN3jJ3S3lqTjpEQhnL/2vCgoiQKbLAx1Z6Pq4a3839zyyK+i2X6GggKzvw7p3e7ZpUT6Mot0zwkhIYpWvsA4nli+ZOkFS69aGsj99X7KCVKCpVtUJGI/cFzj6T3OxVk5RpSq2KvhNsV1I/lsB6l/54Vxvv3fdFdlqQbayaeRlZCTNjpeLfpmmSnR9WkTSvXqpbdwZk17BmTWXfzWV6C6ZamZjAdIyufUpH7QGr3tLea836IJP295dFmtZXTUCe4WwzByv1Jjztx,iv:8BOhQ+KhL++Hz2BDMDmeKOQ5GRGC+YaS0Y6zq3xLVGE=,tag:Nn1rNI+rGoFtr0mbKTvkbw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:542006288021:alias/vrsf-homelab-sops
          created_at: "2024-06-07T21:14:12Z"
          enc: AQICAHgF6injDvjROWdTFk5WjvFDpdnnijlTWIcGuHq8tjJbNgEZw7P9t0iHosNSnRLScguDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqdUaod+LMqXzcCQRAgEQgDuKbVIpwNbOtt7CFMWPzs4Sqvsuq4RO+bHeWHIpY26hGaNcDyH72lDroctEX+DQwARTOxTBkHvVmXTSqg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-07T21:14:12Z"
    mac: ENC[AES256_GCM,data:z62WezhQnhbnUdAPMF5rpRHLw2GPQePb6BxGPo5pYxjjk5McEorvwQ204epg6ZF2Qv8NwqmBWVoV3ldgWTtIyqA7gLEWVI44inbsKQ6kGQMZ65bABf9vjEarVidXFYA6Eoh1Y83dGq6qmBd2zdpv+NpiU3ypyFrud5YX0dnK6Mg=,iv:IekTZQvMBvo6yldI3hrB19v6LsX5OZO+knaMdWkI1R4=,tag:1KBr7Y+VzkVgJgTLFSp/oA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
